SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE cart_items;
TRUNCATE TABLE shopping_carts;
TRUNCATE TABLE order_items;
TRUNCATE TABLE books_categories;
TRUNCATE TABLE books;
TRUNCATE TABLE categories;
TRUNCATE TABLE orders;
TRUNCATE TABLE users;

SET FOREIGN_KEY_CHECKS = 1;